/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * CordorcetMethod.java
 *
 * Created on Nov 18, 2011, 5:35:58 PM
 */
package projectvm;

/**
 *
 * @author Shruti Vangari
 */
public class CordorcetMethod extends javax.swing.JFrame {
public int CW2Name1,CW2Name2;
public int CW3Name1, CW3Name2, CW3Name3;
public int CW4Name1, CW4Name2, CW4Name3, CW4Name4;
int N;
    /** Creates new form CordorcetMethod */
    public CordorcetMethod() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setName("Form"); // NOI18N

        org.jdesktop.application.ResourceMap resourceMap = org.jdesktop.application.Application.getInstance(projectvm.ProjectvmApp.class).getContext().getResourceMap(CordorcetMethod.class);
        jLabel1.setText(resourceMap.getString("jLabel1.text")); // NOI18N
        jLabel1.setName("jLabel1"); // NOI18N

        jScrollPane1.setName("jScrollPane1"); // NOI18N

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jTextArea1.setText(resourceMap.getString("jTextArea1.text")); // NOI18N
        jTextArea1.setName("jTextArea1"); // NOI18N
        jScrollPane1.setViewportView(jTextArea1);

        jButton1.setText(resourceMap.getString("jButton1.text")); // NOI18N
        jButton1.setName("jButton1"); // NOI18N
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText(resourceMap.getString("jButton2.text")); // NOI18N
        jButton2.setName("jButton2"); // NOI18N
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setText(resourceMap.getString("jButton3.text")); // NOI18N
        jButton3.setName("jButton3"); // NOI18N
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jButton1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 512, Short.MAX_VALUE)
                .addComponent(jButton2)
                .addGap(45, 45, 45))
            .addGroup(layout.createSequentialGroup()
                .addGap(41, 41, 41)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 609, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(63, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(293, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(292, 292, 292))
            .addGroup(layout.createSequentialGroup()
                .addGap(308, 308, 308)
                .addComponent(jButton3)
                .addContainerGap(328, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addComponent(jLabel1)
                .addGap(43, 43, 43)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(8, 8, 8)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(46, 46, 46)
                        .addComponent(jButton2))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(jButton3)
                        .addGap(4, 4, 4)
                        .addComponent(jButton1)))
                .addContainerGap(45, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
// TODO add your handling code here:
    
    if(nc.CheckBox2Selected())
    {
        //N=2;
CW2Name1 = d2d.Condorcet2Name1Name2(e2d.Name1, e2d.Name2);
CW2Name2 = d2d.Condorcet2Name2Name1(e2d.Name1, e2d.Name2);
        
        
      
      System.out.printf("%d %d",+CW2Name1, +CW2Name2);
      
      r1.GetCordorcet();
      r1.setVisible(true);
      this.setVisible(false);
      
    }
    if(nc.CheckBox3Selected())
    {
        //N=3;
        
        CW3Name1 = d3d.Condorcet3Name1Name2(e3d.Name1, e3d.Name2) + d3d.Condorcet3Name1Name3(e3d.Name1, e3d.Name3);
        CW3Name2 = d3d.Condorcet3Name2Name1(e3d.Name2, e3d.Name1) + d3d.Condorcet3Name2Name3(e3d.Name2, e3d.Name3);
        CW3Name3 = d3d.Condorcet3Name3Name1(e3d.Name3, e3d.Name1) + d3d.Condorcet3Name3Name2(e3d.Name3, e3d.Name2);
        
        System.out.printf("%d %d %d",+CW3Name1, +CW3Name2, + CW3Name3);
        
        r2.GetCordorcet();
        r2.setVisible(true);
        this.setVisible(false);
     
    }
    
    if(nc.CheckBox4Selected())
    {
        //N=4;
        CW4Name1 = d4d.Condorcet4Name1Name2(e4d.Name1, e4d.Name2) + d4d.Condorcet4Name1Name3(e4d.Name1, e4d.Name3) + d4d.Condorcet4Name1Name4(e4d.Name1, e4d.Name4);
        CW4Name2 = d4d.Condorcet4Name2Name1(e4d.Name1, e4d.Name2) + d4d.Condorcet4Name2Name3(e4d.Name2, e4d.Name3) + d4d.Condorcet4Name2Name4(e4d.Name2, e4d.Name4);
        CW4Name3 = d4d.Condorcet4Name3Name1(e4d.Name1, e4d.Name3) + d4d.Condorcet4Name3Name2(e4d.Name2, e4d.Name3) + d4d.Condorcet4Name3Name4(e4d.Name3, e4d.Name4);
        CW4Name4 = d4d.Condorcet4Name4Name1(e4d.Name1, e4d.Name4) + d4d.Condorcet4Name4Name2(e4d.Name2, e4d.Name4) + d4d.Condorcet4Name4Name3(e4d.Name3, e4d.Name4);
    System.out.printf("%d %d %d %d",+CW4Name1, +CW4Name2, +CW4Name3, +CW4Name4);
    
    r3.GetCordorcet();
    r3.setVisible(true);
    this.setVisible(false);
    
    }
    
}//GEN-LAST:event_jButton3ActionPerformed

private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
// TODO add your handling code here:
    am.setVisible(true);
    this.setVisible(false);
}//GEN-LAST:event_jButton1ActionPerformed

private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
// TODO add your handling code here:
    hp.setVisible(true);
    this.setVisible(false);
}//GEN-LAST:event_jButton2ActionPerformed

  public void InitializeAdminMenuButton(AdminMenu a)
{
    am=a;
}

public void InitializeHomePageButton(HomePage h)
{
    hp=h;
}

public void InitializeCordorcetCalculateButton(NumberCandidates ncc)
{
    nc=ncc;
}

public void InitializeCordorcetCalculateButton(Enter2Data e2)
{
    e2d=e2;
}

public void InitializeCordorcetCalculateButton(Enter3Data e3)
{
    e3d=e3;
}

public void InitializeCordorcetCalculateButton(Enter4Data e4)
{
    e4d=e4;
}

public void InitializeCordorcetCalculateButton(Display2Data d2)
{
    d2d=d2;
}
public void InitializeCordorcetCalculateButton(Display3Data d3)
{
    d3d=d3;
}

public void InitializeCordorcetCalculateButton(Display4Data d4)
{
    d4d=d4;
}

public void InitializeCordorcetCalculateButton(Results1 r11)
{
    r1=r11;
}
public void InitializeCordorcetCalculateButton(Results2 r22)
{
    r2=r22;
}
public void InitializeCordorcetCalculateButton(Results3 r33)
{
    r3=r33;
}

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextArea1;
    // End of variables declaration//GEN-END:variables
AdminMenu am;
HomePage hp;
NumberCandidates nc;
Enter2Data e2d;
Enter3Data e3d;
Enter4Data e4d;
Display2Data d2d;
Display3Data d3d;
Display4Data d4d;
Results1 r1;
Results2 r2;
Results3 r3;
}
