/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * Preference3.java
 *
 * Created on Nov 18, 2011, 7:14:50 PM
 */
package projectvm;
import javax.swing.JOptionPane;

/**
 *
 * @author CPIGA2
 */
public class Preference3 extends javax.swing.JFrame {

    public int Pref3Counter1;
    public int Pref3Counter2;
    public int Pref3Counter3;
    public int Pref3Counter4;
    public int Pref3Counter5;
    public int Pref3Counter6;
//    
//    public int Pref2Counter1;
//public int Pref2Counter2;
    
    /** Creates new form Preference3 */
    public Preference3() {
        initComponents();
    }
public void Disp3Names(String S1,String S2, String S3)
    {
        //1 column
        //jTable1.setValueAt("P1", 0, 0);
        jTable1.setValueAt(S1, 0, 0);
        jTable1.setValueAt(S2, 1, 0);
        jTable1.setValueAt(S3, 2, 0);
        //2 column
        //jTable1.setValueAt("P2", 0, 1);
        jTable1.setValueAt(S1, 0, 1);
        jTable1.setValueAt(S3, 1, 1);
        jTable1.setValueAt(S2, 2, 1);
        //3 column
        //jTable1.setValueAt("P3", 0, 2);
        jTable1.setValueAt(S2, 0, 2);
        jTable1.setValueAt(S1, 1, 2);
        jTable1.setValueAt(S3, 2, 2);
        //4 column
        //jTable1.setValueAt("P4",  0,3);
        jTable1.setValueAt(S2, 0, 3);
        jTable1.setValueAt(S3, 1, 3);
        jTable1.setValueAt(S1, 2, 3);
        //5 column
        //jTable1.setValueAt("P5", 0, 4);
        jTable1.setValueAt(S3, 0, 4);
        jTable1.setValueAt(S1, 1, 4);
        jTable1.setValueAt(S2, 2, 4);
        //6 column
        //jTable1.setValueAt("P6", 0, 5);
        jTable1.setValueAt(S3, 0, 5);
        jTable1.setValueAt(S2, 1, 5);
        jTable1.setValueAt(S1, 2, 5);
    }
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jCheckBox1 = new javax.swing.JCheckBox();
        jCheckBox2 = new javax.swing.JCheckBox();
        jCheckBox3 = new javax.swing.JCheckBox();
        jCheckBox4 = new javax.swing.JCheckBox();
        jCheckBox5 = new javax.swing.JCheckBox();
        jCheckBox6 = new javax.swing.JCheckBox();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setName("Form"); // NOI18N

        org.jdesktop.application.ResourceMap resourceMap = org.jdesktop.application.Application.getInstance(projectvm.ProjectvmApp.class).getContext().getResourceMap(Preference3.class);
        jLabel1.setText(resourceMap.getString("jLabel1.text")); // NOI18N
        jLabel1.setName("jLabel1"); // NOI18N

        jButton2.setText(resourceMap.getString("jButton2.text")); // NOI18N
        jButton2.setName("jButton2"); // NOI18N
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setText(resourceMap.getString("jButton3.text")); // NOI18N
        jButton3.setName("jButton3"); // NOI18N
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jScrollPane1.setName("jScrollPane1"); // NOI18N

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "P1", "P2", "P3", "P4", "P5", "P6"
            }
        ));
        jTable1.setName("jTable1"); // NOI18N
        jScrollPane1.setViewportView(jTable1);
        jTable1.getColumnModel().getColumn(0).setHeaderValue(resourceMap.getString("jTable1.columnModel.title0")); // NOI18N
        jTable1.getColumnModel().getColumn(1).setHeaderValue(resourceMap.getString("jTable1.columnModel.title1")); // NOI18N
        jTable1.getColumnModel().getColumn(2).setHeaderValue(resourceMap.getString("jTable1.columnModel.title2")); // NOI18N
        jTable1.getColumnModel().getColumn(3).setHeaderValue(resourceMap.getString("jTable1.columnModel.title3")); // NOI18N
        jTable1.getColumnModel().getColumn(4).setHeaderValue(resourceMap.getString("jTable1.columnModel.title4")); // NOI18N
        jTable1.getColumnModel().getColumn(5).setHeaderValue(resourceMap.getString("jTable1.columnModel.title5")); // NOI18N

        jCheckBox1.setText(resourceMap.getString("jCheckBox1.text")); // NOI18N
        jCheckBox1.setName("jCheckBox1"); // NOI18N
        jCheckBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBox1ActionPerformed(evt);
            }
        });

        jCheckBox2.setText(resourceMap.getString("jCheckBox2.text")); // NOI18N
        jCheckBox2.setName("jCheckBox2"); // NOI18N
        jCheckBox2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBox2ActionPerformed(evt);
            }
        });

        jCheckBox3.setText(resourceMap.getString("jCheckBox3.text")); // NOI18N
        jCheckBox3.setName("jCheckBox3"); // NOI18N
        jCheckBox3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBox3ActionPerformed(evt);
            }
        });

        jCheckBox4.setText(resourceMap.getString("jCheckBox4.text")); // NOI18N
        jCheckBox4.setName("jCheckBox4"); // NOI18N
        jCheckBox4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBox4ActionPerformed(evt);
            }
        });

        jCheckBox5.setText(resourceMap.getString("jCheckBox5.text")); // NOI18N
        jCheckBox5.setName("jCheckBox5"); // NOI18N
        jCheckBox5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBox5ActionPerformed(evt);
            }
        });

        jCheckBox6.setText(resourceMap.getString("jCheckBox6.text")); // NOI18N
        jCheckBox6.setName("jCheckBox6"); // NOI18N
        jCheckBox6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBox6ActionPerformed(evt);
            }
        });

        jButton1.setText(resourceMap.getString("jButton1.text")); // NOI18N
        jButton1.setName("jButton1"); // NOI18N
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(45, 45, 45)
                .addComponent(jButton2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 341, Short.MAX_VALUE)
                .addComponent(jButton3)
                .addGap(55, 55, 55))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 619, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(272, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(263, 263, 263))
            .addGroup(layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(jCheckBox1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 77, Short.MAX_VALUE)
                .addComponent(jCheckBox2)
                .addGap(73, 73, 73)
                .addComponent(jCheckBox3)
                .addGap(84, 84, 84)
                .addComponent(jCheckBox4)
                .addGap(73, 73, 73)
                .addComponent(jCheckBox5)
                .addGap(68, 68, 68)
                .addComponent(jCheckBox6)
                .addGap(24, 24, 24))
            .addGroup(layout.createSequentialGroup()
                .addGap(278, 278, 278)
                .addComponent(jButton1)
                .addContainerGap(306, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel1)
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jCheckBox1)
                    .addComponent(jCheckBox6)
                    .addComponent(jCheckBox5)
                    .addComponent(jCheckBox4)
                    .addComponent(jCheckBox3)
                    .addComponent(jCheckBox2))
                .addGap(39, 39, 39)
                .addComponent(jButton1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 37, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton2)
                    .addComponent(jButton3))
                .addGap(43, 43, 43))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
// TODO add your handling code here:
    hp.setVisible(true);
    this.setVisible(false);
}//GEN-LAST:event_jButton3ActionPerformed

private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
// TODO add your handling code here:
    uhp.setVisible(true);
    this.setVisible(false);
}//GEN-LAST:event_jButton2ActionPerformed

private void jCheckBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBox1ActionPerformed
// TODO add your handling code here:
}//GEN-LAST:event_jCheckBox1ActionPerformed

private void jCheckBox2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBox2ActionPerformed
// TODO add your handling code here:
}//GEN-LAST:event_jCheckBox2ActionPerformed

private void jCheckBox3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBox3ActionPerformed
// TODO add your handling code here:
}//GEN-LAST:event_jCheckBox3ActionPerformed

private void jCheckBox4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBox4ActionPerformed
// TODO add your handling code here:
}//GEN-LAST:event_jCheckBox4ActionPerformed

private void jCheckBox5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBox5ActionPerformed
// TODO add your handling code here:
}//GEN-LAST:event_jCheckBox5ActionPerformed

private void jCheckBox6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBox6ActionPerformed
// TODO add your handling code here:
}//GEN-LAST:event_jCheckBox6ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        check3();
    }//GEN-LAST:event_jButton1ActionPerformed
public void InitializeUserMenuButton(UserHomePage u)
{
    uhp=u;
}

public void InitializeHomePageButton(HomePage h)
{
    hp=h;
}

public void InitializeDisplayPref(DisplayPreference dpp)
{
    dp=dpp;
}

public void InitializeDisplayPref(Display3Data d3)
{
    d3d=d3;
}

public void InitializeDisplayPref(NumberVoters nvv)
{
    nv=nvv;
}

public void check3()
{
    // TODO add your handling code here:
    if((Pref3Counter1+Pref3Counter2+Pref3Counter3+Pref3Counter4+Pref3Counter5+Pref3Counter6)<nv.CB1())
    {
        if(jCheckBox1.isSelected())
        {
                ++Pref3Counter1;
                System.out.printf("Count is"+Pref3Counter1);
		dp.setVisible(true);
                this.setVisible(false);
                jCheckBox1.setSelected(false);
         }
         
            if(jCheckBox2.isSelected())
            {
                     ++Pref3Counter2;
                    System.out.printf("Count is"+Pref3Counter2);
		    dp.setVisible(true);
                    this.setVisible(false);
                    jCheckBox2.setSelected(false);
                }

            if(jCheckBox3.isSelected())
            {
   
                    ++Pref3Counter3;
                    System.out.printf("Count is"+Pref3Counter3);
		    dp.setVisible(true);
                    this.setVisible(false);
                    jCheckBox3.setSelected(false);
                }
        
            if(jCheckBox4.isSelected())
            {
  
                    ++Pref3Counter4;
                    System.out.printf("Count is"+Pref3Counter4);
		    dp.setVisible(true);
                    this.setVisible(false);
                    jCheckBox4.setSelected(false);
                }

            if(jCheckBox5.isSelected())
            {
   
                    ++Pref3Counter5;
                    System.out.printf("Count is"+Pref3Counter5);
		    dp.setVisible(true);
                    this.setVisible(false);
                    jCheckBox5.setSelected(false);
                }
   
            if(jCheckBox6.isSelected())
            {
                 
                    ++Pref3Counter6;
                    System.out.printf("Count is"+Pref3Counter6);
		    dp.setVisible(true);
                    this.setVisible(false);
                    jCheckBox6.setSelected(false);
                }
             
  
    String A= Integer.toString(Pref3Counter1);
    String B= Integer.toString(Pref3Counter2);
    String C= Integer.toString(Pref3Counter3);
    String D= Integer.toString(Pref3Counter4);
    String E= Integer.toString(Pref3Counter5);
    String F= Integer.toString(Pref3Counter6);
    
    d3d.tableContent1(A);
    d3d.tableContent2(B);
    d3d.tableContent3(C);
    d3d.tableContent4(D);
    d3d.tableContent5(E);
    d3d.tableContent6(F);
    }
    if((Pref3Counter1+Pref3Counter2+Pref3Counter3+Pref3Counter4+Pref3Counter5+Pref3Counter6)>=nv.CB1())
    {
        jCheckBox1.setEnabled(false);
        jCheckBox2.setEnabled(false);
        jCheckBox3.setEnabled(false);
        jCheckBox4.setEnabled(false);
        jCheckBox5.setEnabled(false);
        jCheckBox6.setEnabled(false);
        JOptionPane.showMessageDialog(null,"Voting Closed!!");
    }    
           
    }
 
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JCheckBox jCheckBox1;
    private javax.swing.JCheckBox jCheckBox2;
    private javax.swing.JCheckBox jCheckBox3;
    private javax.swing.JCheckBox jCheckBox4;
    private javax.swing.JCheckBox jCheckBox5;
    private javax.swing.JCheckBox jCheckBox6;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables
UserHomePage uhp;
HomePage hp;
DisplayPreference dp;
Display3Data d3d;
NumberVoters nv;
//Display2Data d2d;
}
