/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * Results2.java
 *
 * Created on Nov 21, 2011, 7:15:52 PM
 */
package projectvm;
import javax.swing.JOptionPane;
/**
 *
 * @author Shruti Vangari
 */
public class Results2 extends javax.swing.JFrame {

    /** Creates new form Results2 */
    public Results2() {
        initComponents();
    }
    
      public void GetBorda()
    {
        jTable1.setValueAt(bm.BC3Name1, 0, 2);
        jTable1.setValueAt(bm.BC3Name2, 1, 2);
        jTable1.setValueAt(bm.BC3Name3, 2, 2);
        jTable1.setValueAt(e3d.Name1, 0, 1);
        jTable1.setValueAt(e3d.Name2,1 ,1 );
        jTable1.setValueAt(e3d.Name3,2 ,1 );
        jTable1.setValueAt("BC(Candidate1)", 0, 0);
        jTable1.setValueAt("BC(Candidate2)", 1, 0);
        jTable1.setValueAt("BC(Candidate3)", 2, 0);
        
    }
      
      public void GetCordorcet()
    {
        jTable1.setValueAt(cm.CW3Name1, 0, 2);
        jTable1.setValueAt(cm.CW3Name2, 1, 2);
        jTable1.setValueAt(cm.CW3Name3, 2, 2);
        jTable1.setValueAt(e3d.Name1, 0, 1);
        jTable1.setValueAt(e3d.Name2,1 ,1 );
        jTable1.setValueAt(e3d.Name3,2 ,1 );
        jTable1.setValueAt("CW(Candidate1)", 0, 0);
        jTable1.setValueAt("CW(Candidate2)", 1, 0);
        jTable1.setValueAt("CW(Candidate3)", 2, 0);
        
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jTextField1 = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jButton3 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setName("Form"); // NOI18N

        org.jdesktop.application.ResourceMap resourceMap = org.jdesktop.application.Application.getInstance(projectvm.ProjectvmApp.class).getContext().getResourceMap(Results2.class);
        jButton1.setText(resourceMap.getString("jButton1.text")); // NOI18N
        jButton1.setName("jButton1"); // NOI18N
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText(resourceMap.getString("jButton2.text")); // NOI18N
        jButton2.setName("jButton2"); // NOI18N
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jLabel1.setText(resourceMap.getString("jLabel1.text")); // NOI18N
        jLabel1.setName("jLabel1"); // NOI18N

        jScrollPane1.setName("jScrollPane1"); // NOI18N

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Function Name", "Name", "Function Value"
            }
        ));
        jTable1.setName("jTable1"); // NOI18N
        jScrollPane1.setViewportView(jTable1);
        jTable1.getColumnModel().getColumn(0).setHeaderValue(resourceMap.getString("jTable1.columnModel.title0")); // NOI18N
        jTable1.getColumnModel().getColumn(1).setHeaderValue(resourceMap.getString("jTable1.columnModel.title1")); // NOI18N
        jTable1.getColumnModel().getColumn(2).setHeaderValue(resourceMap.getString("jTable1.columnModel.title2")); // NOI18N

        jTextField1.setText(resourceMap.getString("jTextField1.text")); // NOI18N
        jTextField1.setName("jTextField1"); // NOI18N

        jLabel2.setText(resourceMap.getString("jLabel2.text")); // NOI18N
        jLabel2.setName("jLabel2"); // NOI18N

        jButton3.setText(resourceMap.getString("jButton3.text")); // NOI18N
        jButton3.setName("jButton3"); // NOI18N
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(jButton1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 369, Short.MAX_VALUE)
                .addComponent(jButton2)
                .addGap(28, 28, 28))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(268, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(247, 247, 247))
            .addGroup(layout.createSequentialGroup()
                .addGap(129, 129, 129)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 375, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(93, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(171, Short.MAX_VALUE)
                .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 267, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(159, 159, 159))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(277, Short.MAX_VALUE)
                .addComponent(jLabel2)
                .addGap(276, 276, 276))
            .addGroup(layout.createSequentialGroup()
                .addGap(259, 259, 259)
                .addComponent(jButton3)
                .addContainerGap(233, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addComponent(jLabel1)
                .addGap(47, 47, 47)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(11, 11, 11)
                .addComponent(jButton3)
                .addGap(18, 18, 18)
                .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, 14, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(jButton2))
                .addGap(39, 39, 39))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
// TODO add your handling code here:
    am.setVisible(true);
    this.setVisible(false);
    jTextField1.setText(null);
}//GEN-LAST:event_jButton1ActionPerformed

private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
// TODO add your handling code here:
    hp.setVisible(true);
    this.setVisible(false);
    jTextField1.setText(null);
}//GEN-LAST:event_jButton2ActionPerformed

private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
// TODO add your handling code here:
    
    if(ms.BordaSelected())
    {
        Borda();
    }
    
    if(ms.CordorcetSelected())
    {
        Cordorcet3();
    }
}//GEN-LAST:event_jButton3ActionPerformed
public void InitializeAdminMenuButton(AdminMenu a)
{
    am=a;
}

public void InitializeHomePageButton(HomePage h)
{
    hp=h;
}

public void DeclareWinner(BordaMethod bmm)
{
    bm=bmm;
}

public void DeclareWinner(Enter3Data e3)
{
    e3d=e3;
}


public void DeclareWinner(MethodSelection mss)
{
    ms=mss;
}


public void DeclareWinner(CordorcetMethod cmm)
{
    cm=cmm;
}

public void Borda()
{
    if((bm.BC3Name1 > bm.BC3Name2) && (bm.BC3Name1 > bm.BC3Name3))
        {
            jTextField1.setText(e3d.Name1);
        }
        if((bm.BC3Name2 > bm.BC3Name3) && (bm.BC3Name2 > bm.BC3Name1))
        {
            jTextField1.setText(e3d.Name2);
        }
        if((bm.BC3Name3 > bm.BC3Name1) && (bm.BC3Name3 > bm.BC3Name2))
        {
            jTextField1.setText(e3d.Name3);
        }
}

public void Cordorcet3()
{
    if((cm.CW3Name1 > cm.CW3Name2) && (cm.CW3Name1 > cm.CW3Name3))
          {
              jTextField1.setText(e3d.Name1);
          }
          
          if((cm.CW3Name2 > cm.CW3Name1) && (cm.CW3Name2 > cm.CW3Name3))
          {
              jTextField1.setText(e3d.Name2);
          }
          
          if((cm.CW3Name3 > cm.CW3Name1) && (cm.CW3Name3 > cm.CW3Name2))
          {
              jTextField1.setText(e3d.Name3);
          }
          if ((cm.CW3Name1 > cm.CW3Name3) && (cm.CW3Name1 == cm.CW3Name2))
          {
              jTextField1.setText("Tie in between Candidate 1 and 2");
          }
          
          if ((cm.CW3Name2 > cm.CW3Name1) && (cm.CW3Name2 == cm.CW3Name3))
          {
              jTextField1.setText("Tie in between Candidate 2 and 3");
          }
          
          if ((cm.CW3Name3 > cm.CW3Name2) && (cm.CW3Name3 == cm.CW3Name1))
          {
              jTextField1.setText("Tie in between Candidate 1 and 3");
          }
}

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField jTextField1;
    // End of variables declaration//GEN-END:variables

AdminMenu am;
HomePage hp;
BordaMethod bm;
Enter3Data e3d;
MethodSelection ms;
CordorcetMethod cm;
}
