/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * Results3.java
 *
 * Created on Nov 21, 2011, 7:16:12 PM
 */
package projectvm;

/**
 *
 * @author Shruti Vangari
 */
public class Results3 extends javax.swing.JFrame {

    /** Creates new form Results3 */
    public Results3() {
        initComponents();
    }
    
      public void GetBorda()
    {
        jTable1.setValueAt(bm.BC4Name1, 0, 2);
        jTable1.setValueAt(bm.BC4Name2, 1, 2);
        jTable1.setValueAt(bm.BC4Name3, 2, 2);
        jTable1.setValueAt(bm.BC4Name4, 3, 2);
        jTable1.setValueAt(e4d.Name1, 0, 1);
        jTable1.setValueAt(e4d.Name2,1 ,1 );
        jTable1.setValueAt(e4d.Name3,2 ,1 );
        jTable1.setValueAt(e4d.Name4,3 ,1 );
        jTable1.setValueAt("BC(Candidate1)", 0, 0);
        jTable1.setValueAt("BC(Candidate2)", 1, 0);
        jTable1.setValueAt("BC(Candidate3)", 2, 0);
        jTable1.setValueAt("BC(Candidate4)", 3, 0);
    }
      
      public void GetCordorcet()
      {
        jTable1.setValueAt(cm.CW4Name1, 0, 2);
        jTable1.setValueAt(cm.CW4Name2, 1, 2);
        jTable1.setValueAt(cm.CW4Name3, 2, 2);
        jTable1.setValueAt(cm.CW4Name4, 3, 2);
        jTable1.setValueAt(e4d.Name1, 0, 1);
        jTable1.setValueAt(e4d.Name2,1 ,1 );
        jTable1.setValueAt(e4d.Name3,2 ,1 );
        jTable1.setValueAt(e4d.Name4,3 ,1 );
        jTable1.setValueAt("CW(Candidate1)", 0, 0);
        jTable1.setValueAt("CW(Candidate2)", 1, 0);
        jTable1.setValueAt("CW(Candidate3)", 2, 0);
        jTable1.setValueAt("CW(Candidate4)", 3, 0);
      }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jButton3 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setName("Form"); // NOI18N

        org.jdesktop.application.ResourceMap resourceMap = org.jdesktop.application.Application.getInstance(projectvm.ProjectvmApp.class).getContext().getResourceMap(Results3.class);
        jButton1.setText(resourceMap.getString("jButton1.text")); // NOI18N
        jButton1.setName("jButton1"); // NOI18N
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText(resourceMap.getString("jButton2.text")); // NOI18N
        jButton2.setName("jButton2"); // NOI18N
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jLabel1.setText(resourceMap.getString("jLabel1.text")); // NOI18N
        jLabel1.setName("jLabel1"); // NOI18N

        jScrollPane1.setName("jScrollPane1"); // NOI18N

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Function Name", "Name", "Function Value"
            }
        ));
        jTable1.setName("jTable1"); // NOI18N
        jScrollPane1.setViewportView(jTable1);
        jTable1.getColumnModel().getColumn(0).setHeaderValue(resourceMap.getString("jTable1.columnModel.title0")); // NOI18N
        jTable1.getColumnModel().getColumn(1).setHeaderValue(resourceMap.getString("jTable1.columnModel.title1")); // NOI18N
        jTable1.getColumnModel().getColumn(2).setHeaderValue(resourceMap.getString("jTable1.columnModel.title2")); // NOI18N

        jButton3.setText(resourceMap.getString("jButton3.text")); // NOI18N
        jButton3.setName("jButton3"); // NOI18N
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jLabel2.setText(resourceMap.getString("jLabel2.text")); // NOI18N
        jLabel2.setName("jLabel2"); // NOI18N

        jTextField1.setText(resourceMap.getString("jTextField1.text")); // NOI18N
        jTextField1.setName("jTextField1"); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jButton1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 510, Short.MAX_VALUE)
                .addComponent(jButton2)
                .addGap(22, 22, 22))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(179, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 375, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(176, 176, 176))
            .addGroup(layout.createSequentialGroup()
                .addGap(323, 323, 323)
                .addComponent(jLabel1)
                .addContainerGap(325, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(311, 311, 311)
                .addComponent(jButton3)
                .addContainerGap(314, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(341, 341, 341)
                .addComponent(jLabel2)
                .addContainerGap(345, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(242, 242, 242)
                .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 238, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(250, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(jLabel1)
                .addGap(33, 33, 33)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28)
                .addComponent(jButton3)
                .addGap(18, 18, 18)
                .addComponent(jLabel2)
                .addGap(18, 18, 18)
                .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 41, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton2)
                    .addComponent(jButton1))
                .addGap(39, 39, 39))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
// TODO add your handling code here:
    am.setVisible(true);
    this.setVisible(false);
    jTextField1.setText(null);
}//GEN-LAST:event_jButton1ActionPerformed

private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
// TODO add your handling code here:
    hp.setVisible(true);
    this.setVisible(false);
    jTextField1.setText(null);
}//GEN-LAST:event_jButton2ActionPerformed

private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
// TODO add your handling code here:
  if(ms.BordaSelected())
    {
        Borda();
    }
    
    if(ms.CordorcetSelected())
    {
        Cordorcet4();
    }
    
    
}//GEN-LAST:event_jButton3ActionPerformed
public void InitializeAdminMenuButton(AdminMenu a)
{
    am=a;
}

public void InitializeHomePageButton(HomePage h)
{
    hp=h;
}
public void DeclareWinner(BordaMethod bmm)
{
    bm=bmm;
}

public void DeclareWinner(Enter4Data e4)
{
    e4d=e4;
}

public void DeclareWinner(CordorcetMethod cmm)
{
    cm=cmm;
}

public void DeclareWinner(MethodSelection mss)
{
    ms=mss;
}

public void Borda()
{
      if((bm.BC4Name1>bm.BC4Name2)&&(bm.BC4Name1>bm.BC4Name3)&&(bm.BC4Name1>bm.BC4Name4))
    {
        jTextField1.setText(e4d.Name1);
    }
      else if((bm.BC4Name2>bm.BC4Name3)&&(bm.BC4Name2>bm.BC4Name4)&&(bm.BC4Name2>bm.BC4Name1))
    {
        jTextField1.setText(e4d.Name2);
    }
      else if((bm.BC4Name3>bm.BC4Name1)&&(bm.BC4Name3>bm.BC4Name2)&&(bm.BC4Name3>bm.BC4Name4))
    {
        jTextField1.setText(e4d.Name3);
    }
    
       else if((bm.BC4Name4>bm.BC4Name1)&&(bm.BC4Name4>bm.BC4Name2)&&(bm.BC4Name4>bm.BC4Name3))
    {
        jTextField1.setText(e4d.Name4);
    }
}

public void Cordorcet4()
{
    if((cm.CW4Name1 > cm.CW4Name2) && (cm.CW4Name1 > cm.CW3Name3) && (cm.CW4Name1 > cm.CW4Name4))
          {
              jTextField1.setText(e4d.Name1);
          }
          
          if((cm.CW4Name2 > cm.CW4Name1) && (cm.CW4Name2 > cm.CW4Name3) && (cm.CW4Name2 > cm.CW4Name4))
          {
              jTextField1.setText(e4d.Name2);
          }
          
          if((cm.CW4Name3 > cm.CW4Name1) && (cm.CW4Name3 > cm.CW4Name2) && (cm.CW4Name3 > cm.CW4Name4))
          {
              jTextField1.setText(e4d.Name3);
          }
          
          if((cm.CW4Name4 > cm.CW4Name1) && (cm.CW4Name4 > cm.CW4Name2) && (cm.CW4Name4 > cm.CW4Name3))
          {
              jTextField1.setText(e4d.Name4);
          }
          
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField jTextField1;
    // End of variables declaration//GEN-END:variables
AdminMenu am;
HomePage hp;
BordaMethod bm;
Enter4Data e4d;
CordorcetMethod cm;
MethodSelection ms;
}
