/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * UserHomePage.java
 *
 * Created on Nov 18, 2011, 12:58:49 AM
 */
package projectvm;
import java.io.*;
/**
 *
 * @author Shruti Vangari
 */
public class UserHomePage extends javax.swing.JFrame {

    /** Creates new form UserHomePage */
    public UserHomePage() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jRadioButton1 = new javax.swing.JRadioButton();
        jRadioButton2 = new javax.swing.JRadioButton();
        jRadioButton3 = new javax.swing.JRadioButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setName("Form"); // NOI18N

        org.jdesktop.application.ResourceMap resourceMap = org.jdesktop.application.Application.getInstance(projectvm.ProjectvmApp.class).getContext().getResourceMap(UserHomePage.class);
        jLabel1.setText(resourceMap.getString("jLabel1.text")); // NOI18N
        jLabel1.setName("jLabel1"); // NOI18N

        jRadioButton1.setText(resourceMap.getString("jRadioButton1.text")); // NOI18N
        jRadioButton1.setName("jRadioButton1"); // NOI18N
        jRadioButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton1ActionPerformed(evt);
            }
        });

        jRadioButton2.setText(resourceMap.getString("jRadioButton2.text")); // NOI18N
        jRadioButton2.setName("jRadioButton2"); // NOI18N
        jRadioButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton2ActionPerformed(evt);
            }
        });

        jRadioButton3.setText(resourceMap.getString("jRadioButton3.text")); // NOI18N
        jRadioButton3.setName("jRadioButton3"); // NOI18N
        jRadioButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton3ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(160, 160, 160)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(135, 135, 135)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jRadioButton2)
                            .addComponent(jRadioButton1)
                            .addComponent(jRadioButton3))))
                .addContainerGap(150, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(43, 43, 43)
                .addComponent(jLabel1)
                .addGap(37, 37, 37)
                .addComponent(jRadioButton1)
                .addGap(33, 33, 33)
                .addComponent(jRadioButton2)
                .addGap(35, 35, 35)
                .addComponent(jRadioButton3)
                .addContainerGap(69, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

private void jRadioButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton1ActionPerformed
// TODO add your handling code here:
    
    //System.out.printf("User Home Page %b %b %b \n", nc.CheckBox2Selected(), nc.CheckBox3Selected(), nc.CheckBox4Selected());
   
    if(nc.CheckBox2Selected())
    {
        d2.setVisible(true);
        this.setVisible(false);
    }
    if(nc.CheckBox3Selected())
    {
        d3.setVisible(true);
        this.setVisible(false);
    }
    
    if(nc.CheckBox4Selected())
    {
        d4.setVisible(true);
        this.setVisible(false);
    }
   
   
}//GEN-LAST:event_jRadioButton1ActionPerformed

private void jRadioButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton2ActionPerformed
// TODO add your handling code here:
    
     //System.out.printf("User Set Preference %b %b %b", nc.CheckBox2Selected(), nc.CheckBox3Selected(), nc.CheckBox4Selected());
    if(nc.CheckBox2Selected())
    {
        p2.setVisible(true);
        this.setVisible(false);
    }
    if(nc.CheckBox3Selected())
    {
        p3.setVisible(true);
        this.setVisible(false);
    }
    
    if(nc.CheckBox4Selected())
    {
        p4.setVisible(true);
        this.setVisible(false);
    }
}//GEN-LAST:event_jRadioButton2ActionPerformed

private void jRadioButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton3ActionPerformed
// TODO add your handling code here:
    dp.setVisible(true);
    this.setVisible(false);
}//GEN-LAST:event_jRadioButton3ActionPerformed

public void InitializeNoCandidatesRB (NumberCandidates c)
{
    nc = c;
}

public void InitializeDisplayCRB(Display2Names d2n)
{
    d2 = d2n;
}

public void InitializeDisplayCRB(Display3Names d3n)
{
    d3 = d3n;
}

public void InitializeDisplayCRB(Display4Names d4n)
{
    d4 = d4n;
}

public void InitializePreferenceRB(Preference2 p2p)
{
    p2 = p2p;
}

public void InitializePreferenceRB(Preference3 p3p)
{
    p3 = p3p;
}

public void InitializePreferenceRB(Preference4 p4p)
{
    p4 = p4p;
}

public void InitializeDisplayPRB(DisplayPreference dpp)
{
    dp=dpp;
}

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JRadioButton jRadioButton1;
    private javax.swing.JRadioButton jRadioButton2;
    private javax.swing.JRadioButton jRadioButton3;
    // End of variables declaration//GEN-END:variables
NumberCandidates nc;
Display2Names d2;
Display3Names d3;
Display4Names d4;
Preference2 p2;
Preference3 p3;
Preference4 p4;
DisplayPreference dp;
}
